services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_ideal_ratings
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql
  technicaltaskidealratingsdotnet:
    image: technicaltaskidealratingsdotnet
    ports:
      - "5009:80"
    build:
      context: .
      dockerfile: TechnicalTaskIdealRatingsDotNet/Dockerfile

volumes: 
  mssql_data: {}